import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VisualEditsMessenger } from "orchids-visual-edits";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lucky Bear Casino — официальный сайт казино Лаки Бир",
  description:
    "Lucky Bear Casino — официальный сайт. Лаки Бир казино: регистрация, бонусы до 360%, быстрые выплаты, тысячи слотов. Вход через сайт или Telegram.",
  keywords:
    "лаки бир, lucky bear casino, казино лаки бир, лаки бир официальный сайт, lucky bear вход, лаки бир регистрация, лаки бир бонус, лаки бир играть онлайн, lucky bear зеркало",
  robots: "index, follow",
  openGraph: {
    title: "Lucky Bear Casino — официальный сайт казино Лаки Бир",
    description:
      "Лаки Бир казино — регистрация, бонусы до 360%, мгновенные выплаты, тысячи слотов.",
    type: "website",
    locale: "ru_RU",
  },
>>>>>>> 316b9c18e834a61e70fec81a83ff2ab9fd09be36
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <VisualEditsMessenger />
=======
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className={inter.variable}>
      <body className="antialiased">
        {children}
          
>>>>>>> 316b9c18e834a61e70fec81a83ff2ab9fd09be36
      </body>
    </html>
  );
}
